SEGFORMERS = {
    "nvidia/segformer-b0-finetuned-ade-512-512": {
        "return_dict": True,
        "output_hidden_states": False,
        "output_attentions": False,
        "torchscript": False,
        "torch_dtype": "float32",
        "use_bfloat16": False,
        "pruned_heads": {},
        "tie_word_embeddings": True,
        "is_encoder_decoder": False,
        "is_decoder": False,
        "cross_attention_hidden_size": None,
        "add_cross_attention": False,
        "tie_encoder_decoder": False,
        "max_length": 20,
        "min_length": 0,
        "do_sample": False,
        "early_stopping": False,
        "num_beams": 1,
        "num_beam_groups": 1,
        "diversity_penalty": 0.0,
        "temperature": 1.0,
        "top_k": 50,
        "top_p": 1.0,
        "typical_p": 1.0,
        "repetition_penalty": 1.0,
        "length_penalty": 1.0,
        "no_repeat_ngram_size": 0,
        "encoder_no_repeat_ngram_size": 0,
        "bad_words_ids": None,
        "num_return_sequences": 1,
        "chunk_size_feed_forward": 0,
        "output_scores": False,
        "return_dict_in_generate": False,
        "forced_bos_token_id": None,
        "forced_eos_token_id": None,
        "remove_invalid_values": False,
        "exponential_decay_length_penalty": None,
        "architectures": ["SegformerForSemanticSegmentation"],
        "finetuning_task": None,
        "tokenizer_class": None,
        "prefix": None,
        "bos_token_id": None,
        "pad_token_id": None,
        "eos_token_id": None,
        "sep_token_id": None,
        "decoder_start_token_id": None,
        "task_specific_params": None,
        "problem_type": None,
        "transformers_version": "4.19.3",
        "downsampling_rates": [1, 4, 8, 16],
        "image_size": 224,
        "model_type": "segformer",
        "reshape_last_stage": True,
        "num_channels": 3,
        "num_encoder_blocks": 4,
        "depths": [2, 2, 2, 2],
        "sr_ratios": [8, 4, 2, 1],
        "hidden_sizes": [32, 64, 160, 256],
        "patch_sizes": [7, 3, 3, 3],
        "strides": [4, 2, 2, 2],
        "mlp_ratios": [4, 4, 4, 4],
        "num_attention_heads": [1, 2, 5, 8],
        "hidden_act": "gelu",
        "hidden_dropout_prob": 0.0,
        "attention_probs_dropout_prob": 0.0,
        "classifier_dropout_prob": 0.1,
        "initializer_range": 0.02,
        "drop_path_rate": 0.1,
        "layer_norm_eps": 1e-06,
        "decoder_hidden_size": 256,
        "semantic_loss_ignore_index": 255,
    },
    "nvidia/segformer-b5-finetuned-ade-640-640": {
        "return_dict": True,
        "output_hidden_states": False,
        "output_attentions": False,
        "torchscript": False,
        "torch_dtype": "float32",
        "use_bfloat16": False,
        "pruned_heads": {},
        "tie_word_embeddings": True,
        "is_encoder_decoder": False,
        "is_decoder": False,
        "cross_attention_hidden_size": None,
        "add_cross_attention": False,
        "tie_encoder_decoder": False,
        "max_length": 20,
        "min_length": 0,
        "do_sample": False,
        "early_stopping": False,
        "num_beams": 1,
        "num_beam_groups": 1,
        "diversity_penalty": 0.0,
        "temperature": 1.0,
        "top_k": 50,
        "top_p": 1.0,
        "typical_p": 1.0,
        "repetition_penalty": 1.0,
        "length_penalty": 1.0,
        "no_repeat_ngram_size": 0,
        "encoder_no_repeat_ngram_size": 0,
        "bad_words_ids": None,
        "num_return_sequences": 1,
        "chunk_size_feed_forward": 0,
        "output_scores": False,
        "return_dict_in_generate": False,
        "forced_bos_token_id": None,
        "forced_eos_token_id": None,
        "remove_invalid_values": False,
        "exponential_decay_length_penalty": None,
        "architectures": ["SegformerForSemanticSegmentation"],
        "finetuning_task": None,
        "tokenizer_class": None,
        "prefix": None,
        "bos_token_id": None,
        "pad_token_id": None,
        "eos_token_id": None,
        "sep_token_id": None,
        "decoder_start_token_id": None,
        "task_specific_params": None,
        "problem_type": None,
        "transformers_version": "4.19.3",
        "downsampling_rates": [1, 4, 8, 16],
        "image_size": 224,
        "model_type": "segformer",
        "reshape_last_stage": True,
        "num_channels": 3,
        "num_encoder_blocks": 4,
        "depths": [3, 6, 40, 3],
        "sr_ratios": [8, 4, 2, 1],
        "hidden_sizes": [64, 128, 320, 512],
        "patch_sizes": [7, 3, 3, 3],
        "strides": [4, 2, 2, 2],
        "mlp_ratios": [4, 4, 4, 4],
        "num_attention_heads": [1, 2, 5, 8],
        "hidden_act": "gelu",
        "hidden_dropout_prob": 0.0,
        "attention_probs_dropout_prob": 0.0,
        "classifier_dropout_prob": 0.1,
        "initializer_range": 0.02,
        "drop_path_rate": 0.1,
        "layer_norm_eps": 1e-06,
        "decoder_hidden_size": 768,
        "semantic_loss_ignore_index": 255,
    },
    "nvidia/segformer-b5-finetuned-cityscapes-1024-1024": {
        "return_dict": True,
        "output_hidden_states": False,
        "output_attentions": False,
        "torchscript": False,
        "torch_dtype": "float32",
        "use_bfloat16": False,
        "pruned_heads": {},
        "tie_word_embeddings": True,
        "is_encoder_decoder": False,
        "is_decoder": False,
        "cross_attention_hidden_size": None,
        "add_cross_attention": False,
        "tie_encoder_decoder": False,
        "max_length": 20,
        "min_length": 0,
        "do_sample": False,
        "early_stopping": False,
        "num_beams": 1,
        "num_beam_groups": 1,
        "diversity_penalty": 0.0,
        "temperature": 1.0,
        "top_k": 50,
        "top_p": 1.0,
        "typical_p": 1.0,
        "repetition_penalty": 1.0,
        "length_penalty": 1.0,
        "no_repeat_ngram_size": 0,
        "encoder_no_repeat_ngram_size": 0,
        "bad_words_ids": None,
        "num_return_sequences": 1,
        "chunk_size_feed_forward": 0,
        "output_scores": False,
        "return_dict_in_generate": False,
        "forced_bos_token_id": None,
        "forced_eos_token_id": None,
        "remove_invalid_values": False,
        "exponential_decay_length_penalty": None,
        "architectures": ["SegformerForSemanticSegmentation"],
        "finetuning_task": None,
        "tokenizer_class": None,
        "prefix": None,
        "bos_token_id": None,
        "pad_token_id": None,
        "eos_token_id": None,
        "sep_token_id": None,
        "decoder_start_token_id": None,
        "task_specific_params": None,
        "problem_type": None,
        "transformers_version": "4.19.3",
        "downsampling_rates": [1, 4, 8, 16],
        "image_size": 224,
        "model_type": "segformer",
        "reshape_last_stage": True,
        "num_channels": 3,
        "num_encoder_blocks": 4,
        "depths": [3, 6, 40, 3],
        "sr_ratios": [8, 4, 2, 1],
        "hidden_sizes": [64, 128, 320, 512],
        "patch_sizes": [7, 3, 3, 3],
        "strides": [4, 2, 2, 2],
        "mlp_ratios": [4, 4, 4, 4],
        "num_attention_heads": [1, 2, 5, 8],
        "hidden_act": "gelu",
        "hidden_dropout_prob": 0.0,
        "attention_probs_dropout_prob": 0.0,
        "classifier_dropout_prob": 0.1,
        "initializer_range": 0.02,
        "drop_path_rate": 0.1,
        "layer_norm_eps": 1e-06,
        "decoder_hidden_size": 768,
        "semantic_loss_ignore_index": 255,
    },
}
